services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - C:/Users/User/Desktop/docker-practice/frontend/src:/app/src
    restart: always
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./backend
    volumes:
      - C:/Users/User/Desktop/docker-practice/backend:/app
      - ./backend/logs:/app/logs
      - ./backend/node_modules:/app/node_modules
    depends_on:
      - mongodb-app
    networks:
      - application-network
    ports:
      - 80:80
    expose: 
      - 80

  mongodb-app:
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - application-network
    expose:
      - 27017
networks:
  application-network: